[project]
name = "tgfuse"
version = "0.1.0"
description = "Tg Bot/UserBot that allows you to mount a telegram channel as a drive in linux using fuse."
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "pyfuse3>=3.4.0",
    "telethon>=1.36.0",
    "cryptg>=0.5",
    "aiosqlite>=0.20.0"
]

[project.scripts]
tgfuse = "tgfuse.__main__:run"

[tool.pyright]
venvPath = '.'
venv = '.venv'